---

- name: copy nginx.repo
  copy:
    src: nginx.repo
    dest: /etc/yum.repos.d/nginx.repo

- name: install nginx
  dnf:
    name: nginx
    state: latest

- name: copy default.conf
  copy:
    src: default.conf
    dest: /etc/nginx/conf.d/default.conf
    force: yes

- name: enable and start nginx
  systemd:
    name: nginx
    state: started
    enabled: yes